---
title: "Handle batch processing and export pipelines using the API"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{api_jobs}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  message = FALSE, 
  warning = FALSE
)

library(tidyverse)
library(httr)
library(rpigraf)

api_setup("http://localhost", "devel")

```


# Example for downloading data from an export job

In this example, the pipeline (ID 471) needs to be finished with a download task
that contains two download files

```{r eval=FALSE}

job <- api_job_create(
  endpoint = "articles/export", 
  params = list(projects=20, pipeline=471, id=2508), 
  database = "epi_playground",
  payload = list(config=list(options=list(sort_signatures=0)))
)


downloads <- job$downloads

api_download(downloads$url[1], filename = downloads$name[1])
api_download(downloads$url[2], filename = downloads$name[2])


```

