---
title: "Import data into Epigraf"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{import}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  message = FALSE, 
  warning = FALSE
)

library(tidyverse)
library(dplyr)
library(tibble)
library(eprgraf)

api_setup("http://localhost", "devel")

```

Epigraf expects data in a format called Relational Article Model (RAM).


## Upload data

### Map data to the RAM

```{r}

ds <- tribble(
  ~case, ~title,       ~genre,     ~text,
  "011", "Westworld",   "Western", "In a futuristic amusement park, androids populate themed worlds like the Wild West.",
  "012", "Yellowstone", "Western", "Ranch owner John Dutton battles to protect his family's massive Montana cattle ranch.",
  "013", "Once Upon",   "Western", "A mysterious harmonica-playing stranger teams up with a bandit."
)

# The project is named "Movies". The type defaults to "default".
ds <- df_to_ram(ds, project.fill = c("fragment" = "movies", "name" = "Movies", "signature"="movies"))

# Article data is taken from the columns: case, title. The type defaults to "default".
ds <- df_to_ram(ds, article.cols = c("fragment" = "case", "signature" = "case", "name" = "title"))
    
# The text section is named "Abstract"
ds <- df_to_ram(ds, section.fill = c("type" = "text", "name" = "Abstract"))

# The text item data is taken from the columns: text. The type is fixed to "text".
ds <- df_to_ram(ds, item.fill = c("type" = "text"), item.cols = c("content" = "text"))

# The categories section is named "Genres". The type is fixed to "categories".
ds <- df_to_ram(ds, section.fill = c("type" = "categories", "name" = "Genres"))
        
# The categories property content is taken from the columns: genre.
ds <- df_to_ram(ds, property.cols = c("fragment"="genre", "lemma" = "genre"), property.fill = c("type" = "categories"))

# The categories item content is taken from the columns: .property was created by the property mapping beforehand.
ds <- df_to_ram(ds, item.cols = c("properties_id" = ".property"), item.fill = c("type" = "categories"))

# Compile the stacked ram rows
epi <- ram_compile(ds)

```

### Patch data into the database

```{r eval=FALSE}
api_patch(epi, db = "epi_movies")
```


## Download data

### Fetch data
```{r eval=FALSE}

epi <- api_fetch("articles", db = "epi_movies")

```

### Work with RAM data
```{r eval=FALSE}

distill_articles(epi, c("signature", "name"), item.type = "categories", property.cols = "lemma")

distill_articles(epi, c("name","signature"), item.type = "text", item.cols = "content")

distill_properties(epi, "annotations", annos = TRUE)

```
